apiVersion: apps/v1
kind: Deployment
metadata:
  name: consent-manager
  namespace: nha-app
  labels:
        app: consent-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consent-manager
  template:
    metadata:
      labels:
        app: consent-manager
    spec:
      containers:
      - name: consent-manager
        image: ganesan92/consent-manager:92f47fd
        env:
          - name: AUTH_SERVER_URL
            value: http://client-registry:8080
          - name: Auth_Token
            value: f9287684-d3ab-4974-bcfe-2b65f6a5022c
          - name: CENTRAL_REGISTRY_ID
            value: ncg
          - name: CENTRAL_REGISTRY_JWK_URL
            value: http://client-registry:8080/certs
          - name: CONSENT_EXPIRY_CRON_EXPRESSION
            value: 0 0 * ? * *
          - name: CONSENT_MANAGER_DB_NAME
            value: consent_manager
          - name: CONSENT_MANAGER_URL
            value: http://localhost:8000
          - name: CONSENT_REQUEST_EXPIRY
            value: "60"
          - name: CONSENT_REQUEST_EXPIRY_CRON_EXPRESSION
            value: 0 0 0/12 ? * *
          - name: CONSENT_SERVICE_URL
            value: http://localhost:8000
          - name: COOL_OF_PERIOD
            value: "480"
          - name: Client_Registry_Url
            value: http://client-registry:8080
          - name: DB_CONNECTION_POOL_SIZE
            value: "5"
          - name: DEFAULT_PAGE_SIZE
            value: "20"
          - name: GATEWAY_BASE_URL
            value: http://gateway:8000/v1
          - name: GATEWAY_ENABLED
            value: "true"
          - name: GATEWAY_REQUEST_TIMEOUT
            value: "8000"
          - name: JWT_SECRET
            value: secret
          - name: KEY_CLOAK_CONSENT_CLIENT_ID
            value: ncg
          - name: KEY_CLOAK_CONSENT_CLIENT_SECRET
            value: 40a473c7-fccc-4ffa-9491-796e2e045517
          - name: KEY_CLOAK_CONSENT_PASSWORD
            value: welcome
          - name: KEY_CLOAK_CONSENT_USER_NAME
            value: consent-service-admin-user
          - name: KEY_CLOAK_JWK_URL
            value: http://keycloak:8080/auth/realms/consent-manager/protocol/openid-connect/certs
          - name: KEY_CLOAK_TOKEN_ISSUER
            value: http://keycloak:8080/auth/realms/consent-manager
          - name: KEY_CLOAK_URL
            value: http://keycloak:8080/auth
          - name: LINK_SERVICE_URL
            value: http://localhost:8000
          - name: LINK_TRANSACTION_TIMEOUT
            value: "5000"
          - name: LISTENERS_MAXIMUM_RETRIES
            value: "3"
          - name: LISTENERS_RETRY_INTERVAL
            value: "1000"
          - name: LOG_LOCATION
            value: /applogs/app.log
          - name: MAXIMUM_INVALID_ATTEMPTS
            value: "5"
          - name: MAX_INVALID_OTP_ATTEMPTS
            value: "5"
          - name: MAX_OTP_ATTEMPTS
            value: "5"
          - name: MAX_OTP_ATTEMPTS_PERIOD_IN_MIN
            value: "10"
          - name: MAX_PAGE_SIZE
            value: "100"
          - name: OTP_ATTEMPTS_BLOCK_PERIOD_IN_MIN
            value: "10"
          - name: OTP_EXPIRY_IN_MINUTES
            value: "5"
          - name: OTP_INVALID_ATTEMPT_BLOCK_PERIOD_IN_MIN
            value: "240"
          - name: Otp_Service_Url
            value: http://otp
          - name: POSTGRES_HOST
            value: nhadcl-postges-1.nhadclmgm.tatacommunications.com
          - name: POSTGRES_PASSWORD
            value: "TAta12#$"
          - name: POSTGRES_PORT
            value: "5633"
          - name: POSTGRES_USER
            value: postgres
          - name: RABBITMQ_HOST
            value: rabbitmq
          - name: RABBITMQ_PORT
            value: "5672"
          - name: REDIS_HOST
            value: redis.nhadclmgm.tatacommunications.com
          - name: REDIS_PASSWORD
            value: "TAta12#$"
          - name: TRANSACTION_PIN_DIGIT_SIZE
            value: "4"
          - name: TRANSACTION_PIN_TOKEN_VALIDITY
            value: "2"
          - name: USER_CREATION_TOKEN_VALIDITY
            value: "5"
          - name: USER_ID_SUFFIX
            value: '@ncg'
          - name: User_Service_Url
            value: http://localhost:8000
          - name: GATEWAY_CLIENT_SECRET
            value: de39b3c9-dac2-4b01-ac5c-7fdd02608872
          - name: GATEWAY_CLIENT_ID
            value: ncg
          - name: CENTRAL_REGISTRY_JWK_URL
            value: http://gateway:8000/v1/certs
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
