apiVersion: v1
kind: PersistentVolume
metadata:
  name: demologs-pv
  namespace: nha-app
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/demologs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demolog-pvc
  namespace: nha-app
  labels:
    app: demolog-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
