{{ if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "consent-manager.fullname" . }}-secrets
  labels:
    {{- include "consent-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}